<?php

namespace SymplificaBundle\Repository;

/**
 * tipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoContratoRepository extends \Doctrine\ORM\EntityRepository
{
}
